mutation AddRecord($type: RecordType!, $value: String!, $device: String!, $profile: String!) {
  addRecord(type: $type, value: $value, device: $device, profile: $profile) {
    record {
      inUserId
      userId
      value
      type
      profile
      createdAt
      device
    }
    success
    message
    id
  }
}