mutation addRecord($type: RecordType!, $value: String!, $device: String!, $profile: String!) {
  addRecord(type: $type, value: $value, device: $device, profile: $profile) {
    success
    id
    message
  }
}
