mutation AddRecord($type: RecordType!, $value: String!, $device: String!, $profile: String!) {
  addRecord(type: $type, value: $value, device: $device, profile: $profile) {
    success
    message
    id
    record {
      id
      uuid
      userId
      value
      type
      profile
      createdAt
      device
      expired
      deleted
    }
  }
}