type ClipboardItem {
  id: Int!
  userId: String!
  value: String
  type: String!
  profile: String
  createdAt: String
}

type Query {
  clipboardItems(limit: Int): [ClipboardItem]
  itemsLaterThanId(id: Int!): [ClipboardItem]
}
