type Mutation {
    # Record
    addFileRecord(type: RecordType!, value: String!, device: String!, profile: String!, file: Upload!): AddRecordResponse
    singleUpload(file: Upload!): File!
    addRecord(type: RecordType!, value: String!, device: String!, profile: String!): AddRecordResponse
    deleteRecord(inUserId: Int!): DeleteRecordResponse
    updateRecord(inUserId: Int!, newValue: String!): UpdateRecordResponse
    # User
    login(email: String!, password: String!): LoginResponse
    register(username: String!, email: String!, password: String!, code: String!): RegisterResponse
    addFilter(type: AddFilterListType!, regex: String!): AddFilterResponse
    changeFilterType(type: FilterListType!): ChangeFilterTypeResponse
    addProfile(profile: String!): UpdateProfileResponse
    deleteProfile(profile: String!): UpdateProfileResponse
    deleteFilter(filter: String!, filterListType: FilterListType!): DeleteFilterResponse
    renameProfile(originalProfile: String!, newProfile: String!): RenameProfileResponse
    sendEmailOwnershipVerificationCode(username: String!, email: String!): StandardResponse
    verifyEmailOwnership(username: String!, email: String!, code: String!): VerifyEmailOwnershipResponse
}

type Query {
    # Root
    online: Boolean
    # Record
    records: [Record]
    recordsLaterThanId(id: Int!): [Record]
    # User
    me: User
    userByEmail(email: String!): User
    userById(id: String!): User
    usernameExists(username: String!): Boolean
    emailExists(email: String!): Boolean
}

