enum RecordType {
    TEXT
    IMAGE
}

type Rec {
    id: ID!
    inUserId: Int!
    userId: String!
    value: String!
    type: RecordType!
    profile: String!
    createdAt: String
    device: String!
    expired: Boolean!
    deleted: Boolean!
}

type AddRecordResponse {
    success: Boolean!
    message: String!
    id: Int!
    record: Rec!
}

type DeleteRecordResponse {
    success: Boolean!
    message: String!
}

type UpdateRecordResponse {
    success: Boolean!
    message: String!
    record: Rec!
}

