enum Role {
  USER
  ADMIN
}

enum FilterListType {
  BLACKLIST
  WHITELIST
}

type User {
  _id: String!
  username: String
  email: String!
  createdAt: String
  profiles: [String]
  records: [Record]
  role: Role
  filterListType: FilterListType
  blacklist: [String]!
  whitelist: [String]!
}

type Query {
  me: User
  userByEmail(email: String!): User
  userById(id: String!): User
  usernameExists(username: String!): Boolean
}

type LoginResponse {
  accessToken: String
  user: User
  success: Boolean
  message: String
}

type RegisterResponse {
  success: Boolean
  message: String
}

type Mutation {
  login(email: String!, password: String!): LoginResponse
  register(username: String!, email: String!, password: String!): RegisterResponse
}
