mutation login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    accessToken
    refreshToken
    user {
      id
      username
      email
      createdAt
      profiles
      records {
        id
        uuid
        userId
        value
        type
        profile
        createdAt
        device
        expired
        deleted
      }
      role
      recordCount
      lastRecordId
      recordQuota
      activated
    }
    success
    message
  }
}