mutation signup($username: String!, $email: String!, $password: String!, $code: String!) {
  register(username: $username, email: $email, password: $password, code: $code) {
    success
    message
  }
}
